### ISSUE TITLE
ユーザー情報を表示する

### ISSUE THREAD

**Issue by good1luck21** [miyatheta/sample_app#1]
### 次回までの宿題目標(ユーザー情報を表示する)
**********************
**以下開発方針**
- [x] githubでmaster_miyashitaブランチを作成する。
- [x] `git push` は上記で作成したブランチに対して行う。
- [x] 質問などについては本issueにコメントする形で行う。
**********************
**ブランチ作成手順**
1. github
    1_1. githubのトップページにアクセス
    1_2. フォルダ一覧のページのプルダウンをクリック後、新規ブランチを作成する。
2. local
    2_1. terminalでgit pull
    2_2. git checkout origin/master_miyashita
    2_3. git checkout -b master_miyashita
    2_4. git branch --set-upstream-to=origin/master_miyashita
**********************

**Comment by miyatheta** [comment]
こんばんは。
ユーザーモデル作成３：Userモデルの作成まで進みましたがマイグレーションの実行でつまづき、
一度先日の講義時点までGitからロールバックして再作業しようと試みたのですが、
Gemfile.lockでコンフリクトが起きて下記のようなMessageが表示されてしまいます。

Your Gemfile.lock contains merge conflicts.
Run `git checkout HEAD -- Gemfile.lock` first to get a clean lock.

指定された通りにgit checkout HEAD -- Gemfile.lockを行っても解消しませんでした。

**Comment by miyatheta** [comment]
ユーザー情報を表示するところまでは完了しました。

https://www.dropbox.com/s/j5vx5odxbxyu67u/%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3%E3%82%B7%E3%83%A7%E3%83%83%E3%83%88%202018-03-11%2012.32.51.png?dl=0

しかしrails　のコンソール上でのモデルの操作が上手く行きません。
開発自体は進められますがコンソールからuserの情報を更新したり、削除する際にうまくいきません。

エラー内容や環境よりも、コンソールの操作と、操作時のモデルの状態がちゃんと理解できていないことが原因の気がしますので、本日の講義で画面共有しながら操作を見ていただきたいと思います。

よろしくお願いします。

**Comment by miyatheta** [comment]
Done
